data:
  image: python:3.6
  volumes:
    - ./:/app
    - ./data:/data

# shares volume with other images so we can use COPY
db:
  image: mdillon/postgis:9.6
  environment:
    - POSTGRES_USER=gnaf
    - POSTGRES_PASSWORD=gnaf
  volumes:
    - ./volumes/postgres-data:/var/lib/postgresql/data
  volumes_from:
    - data
  ports:
    - "5432:5432"

loader:
  build: .
  volumes_from:
    - data
  links:
   - db
  ports:
    - "9000"
  tty: true

# http://127.0.0.1:8080/?pgsql=db&username=gnaf&db=gnaf&ns=public
adminer:
  image: adminer
  restart: always
  links:
    - db
  ports:
    - "8080:8080"

# http://localhost:8081/browser/ with login details below and host 'db'
pgadmin:
  image: dpage/pgadmin4
  links:
    - db
  environment:
    PGADMIN_DEFAULT_EMAIL: gnaf@test.com
    PGADMIN_DEFAULT_PASSWORD: gnaf
  volumes:
    - ./volumes/pgadmin:/root/.pgadmin
  ports:
    - "8081:80"

